title: Karen Waggoner # your name (or website title) here
logo: "/images/profilepix.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
Data Analyst based in Metro Atlanta.
<br>
Experienced working with NGOs in Asia, 
collaborating on multicultural teams,
and explaining concepts simply.
<br>
Skilled in Excel/Google Sheets, SQL, & Tableau.
  <br>
  <br><br>
  <a href="https://www.linkedin.com/in/karengwaggoner/">View My LinkedIn Profile</a> 
  <br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
