title: Karen Waggoner # your name (or website title) here
logo: "/images/profile_pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
   <p align = "center">
   Integrity-Driven Data Analyst <br>
   Cleaning & Visualizing with SQL, Excel, & Tableau </p> 
   <br>
   <p align="center">
   <a href="mailto:karen.g.waggoner@gmail.com"><img src="images/email_icon.png?raw=true"/>&nbsp;&nbsp;&nbsp;
   <a href="https://www.linkedin.com/in/karengwaggoner/"><img src="images/linkedin_icon.png?raw=true"/>&nbsp;&nbsp;&nbsp; 
   <a href="https://public.tableau.com/app/profile/karen.waggoner"><img src="images/tableau_icon.png?raw=true"/>&nbsp;&nbsp;&nbsp;
   <a href="/files/KarenWaggoner_DataAnalyst_July.pdf"><img src="images/resume_icon.png?raw=true"/>&nbsp;&nbsp;&nbsp;
   <a href="https://github.com/KarenWaggoner/"><img src="images/github_icon.png?raw=true"/></p>
   <br><br>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

