title: Karen Waggoner # your name (or website title) here
logo: "/images/profile_picture.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst based in Metro Atlanta. 
  Specializing in cleaning and visualization. 
  Experienced training others, collaborating on multicultural teams, and presenting information in understandable ways. 
  Skilled in Excel, Google Sheets, SQL, and Tableau.
  <br><br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here



